

DATA:
    DATASET: kinetics400
    NUM_CLASSES: 400
    ROOT: 'to_specify'
    TRAIN_FILE: 'datasets_splits/k400_splits/clip_match_result_thresh0.9.txt'
    VAL_FILE: 'datasets_splits/k400_splits/val.txt'
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
    DATASET_VAL_ZS: ucf101
    NUM_CLASSES_ZS: 101
    ROOT_VAL_ZS: 'to_specify'
    VAL_ZS_FILE: 'datasets_splits/ucf_splits/val1.txt'
    VAL_ZS_LABEL_LIST: 'labels/ucf_101_labels.csv'
    NUM_FRAMES: 32
    USE_DESCRIPTION: True
    USE_DESCRIPTION_TYPE: 'train cls+cap'
MODEL:
    ARCH: ViT-B/16
    MODEL_PATH: 'to_specify' # path of ViT-B-16.pt
    INIT_TEMPERATURE: 0.02
    MIN_TEMPERATURE: 0.001
TRAIN:
    BATCH_SIZE: 4 # Effective BS 256
    ACCUMULATION_STEPS: 8
    LR: 8e-06
    EPOCHS: 10
    NUM_WORKERS: 12
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
VAL_BATCH_SIZE: 2
SAVE_FREQ: 2
PRINT_FREQ: 50
SEED: 1024