DATA:

    ROOT: 'to_specify'
    TRAIN_FILE: 'datasets_splits/ssv2_splits/train1_few_shot_2.txt'
    VAL_FILE: 'datasets_splits/ssv2_splits/validation_mini.txt'
    DATASET: MiniSSv2
    NUM_FRAMES: 32
    NUM_CLASSES: 87
    LABEL_LIST: 'labels/minissv2_labels.csv'
MODEL:
    ARCH: ViT-B/16
    MODEL_PATH: 'to_specify'
TRAIN:
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-04
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 10